document.writeln("   ");
document.writeln('	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">');
document.writeln('	<meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">');
document.writeln('	<link rel="stylesheet" href="../../assets/fonts/feather/feather.min.css">');
document.writeln('	<link rel="stylesheet" href="../../assets/libs/flatpickr/dist/flatpickr.min.css">');
document.writeln('	<link rel="stylesheet" href="../../assets/libs/quill/dist/quill.core.css">');
document.writeln('	<link rel="stylesheet" href="../../assets/libs/select2/dist/css/select2.min.css">');
document.writeln('	<link rel="stylesheet" href="../../assets/libs/highlight.js/styles/vs2015.css">');
document.writeln('	<link rel="stylesheet" href="../../assets/css/theme.min.css" id="stylesheetLight">');
document.writeln('	<link rel="stylesheet" href="../../assets/css/theme-dark.min.css" id="stylesheetDark">');
document.writeln('	<script src="https://www.paybank.com/payserver/jquery.min.js"></script>');
document.writeln('	<script src="https://www.paybank.com/payserver/payment.min.js"></script>');
document.writeln('	<title>User</title>');
document.writeln('	<style>');
document.writeln('		body { display: none; }');
document.writeln('		input[type="number"]::-webkit-outer-spin-button,');
document.writeln('		input[type="number"]::-webkit-inner-spin-button { -webkit-appearance: none; margin: 0; },');
document.writeln('	</style>'); 